version: "3"

services:
  namenode:
    image: bigdatainf/hadoop-namenode:3.3.5
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./hdfs/namenode:/hadoop/dfs/name
      - ./jobs:/app
    working_dir: /app
    environment:
      - CLUSTER_NAME=test
      - HOME=/app
    env_file:
      - ./hadoop.env

  datanode1:
    image: bigdatainf/hadoop-datanode:3.3.5
    container_name: datanode1
    restart: always    
    volumes:
      - ./hdfs/datanode1:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode2:
    image: bigdatainf/hadoop-datanode:3.3.5
    container_name: datanode2
    restart: always    
    volumes:
      - ./hdfs/datanode2:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  datanode3:
    image: bigdatainf/hadoop-datanode:3.3.5
    container_name: datanode3
    restart: always    
    volumes:
      - ./hdfs/datanode3:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  resourcemanager:
    image: bigdatainf/hadoop-resourcemanager:3.3.5
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode1:9864 datanode2:9864 datanode3:9864"
    env_file:
      - ./hadoop.env

  nodemanager1:
    image: bigdatainf/hadoop-nodemanager:3.3.5
    container_name: nodemanager
    restart: always
    ports:
      - 8042:8042
    environment:
      SERVICE_PRECONDITION: "resourcemanager:8088"
    env_file:
      - ./hadoop.env
